- .github/workflows/build.yml
- .github/workflows/veracode.yml
- charts/conforming-agent/Chart.yaml
- charts/conforming-agent/LICENSE
- charts/provisioning-agent/Chart.yaml
- charts/provisioning-agent/LICENSE
- charts/remoting-agent/Chart.yaml
- charts/remoting-agent/LICENSE
- Adds APACHE licenses to charts. 
- Update dockerhub descriptions in main build
- Debug veracode conditions and api credentials which were incorrectly mixed.
legal considerations.
complete documentation at published registry.
eclipse-tractusx TRG
veracode upload was disabled/muted
Closes #22 
Closes #23
> docs: Fixes some legal, documentation and code analysis glitches 

- .github/workflows/build.yml
- .github/workflows/trivy.yml
- .github/workflows/veracode.yml
- conforming/src/gen/java/org/eclipse/tractusx/agents/conforming/api/SparqlProvider.java
- conforming/src/gen/java/org/eclipse/tractusx/agents/conforming/api/XmlProvider.java
- Improve workflows
- Fix some SAST hints
- SNAPSHOT chart should be able to find SNAPSHOT or latest image
- trivy step was disabled because docker manifest check requires a login
- veracode brought 2 hints (informational, medium) for conforming agent
- veracode did not correctly scan provisioning agent
- veracode did not scan remoting agent at all (https://github.com/eclipse-tractusx/sig-infra/issues/237)
Could you please also start veracode manually after merge (and fixing https://github.com/eclipse-tractusx/sig-infra/issues/237)? Big hug from me!
> chore: trivy, charts, veracode

- DEPENDENCIES
- README.md
- pom.xml
Add a maven plugin for [Eclipse Dash Licenses](https://github.com/eclipse/dash-licenses).
This should make it easier to keep the `DEPENDENCIES` file up-to-date
This is just a suggestion. Running Dash can also be done via standalone .jar.
It seems like the maven setup of this repo makes it slightly more complicated, since the dependencies summary will end up in separate files per module, that need to be merged before running Dash
> Add maven plugin to generate DEPENDENCIES via Dash

- .github/workflows/veracode.yml
- CHANGELOG.md
- DEPENDENCIES
- conforming/src/gen/java/org/eclipse/tractusx/agents/conforming/api/XmlProvider.java
- pom.xml
- provisioning/pom.xml
- provisioning/src/main/docker/Dockerfile
- provisioning/src/test/java/org/eclipse/tractusx/agents/AmazonRdsProxyTest.java
- remoting/src/main/java/org/eclipse/tractusx/agents/remoting/Invocation.java
Addressed four issues from SAST (2*XSLT External Entity Disablement, 2*Discrepancy between unclean maven deps and clean docker runtime)
Already reference upcoming release in CHANGELOG
Include a cloud-based postgres test which reflects a valid deployment scenario (and its current pitfalls).
CHANGELOG should reflect release status (TRG)
Render SAST analysis green and close to 100%
include test settings from E2E tests.
> docs|fix|chore(provisioning-agent): SAST Flaws and CHANGELOG

- .github/workflows/build.yml
- .github/workflows/helm-chart-lint.yml
- .github/workflows/helm-chart-release.yml
- .github/workflows/kics.yml
Fixes four workflows
Workflows did not trigger on release branch
> chore: trigger build/helm and kics on 'release' branch prefix not 're…leases'

- .github/workflows/helm-chart-lint.yml
use the event branch instead of the repository default branch in chart linting and testuing.
chart liniting fails on release branches when comparing against a version-higher main.
> fix(chart-lint): Use the event branch as the linting and change reference

- .github/workflows/helm-chart-lint.yml
see title. last try to fix this shit.
github.event.ref is empty on push
see https://stackoverflow.com/questions/62779643/how-to-extract-branch-name-on-delete-event-github-actions
> fix(chart-lint): should work on push and pull requests

- .github/workflows/build.yml
- .github/workflows/helm-chart-lint.yml
- .github/workflows/helm-chart-release.yml
- .github/workflows/kics.yml
This PR fixes the build workflow trigger declarations. The `tags` have previously been defined for `workflow_dispatch`, but this event type does not take other arguments than `input`. See [docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)
Creating a git tag in the `release/1.9.8` branch did not trigger any builds. The new declaration should fix that
`v1.9.8` tag was deleted again. When the changes are merged, we should be able to just re-create it
> fix(build): trigger build workflow on pushed tags

- .github/workflows/build.yml
- .github/workflows/helm-chart-lint.yml
- .github/workflows/helm-chart-release.yml
- .github/workflows/kics.yml
- .github/workflows/trivy.yml
- .github/workflows/veracode.yml
- remoting/pom.xml
- remoting/src/main/docker/Dockerfile
Manual triggering of the build workflow now comes with deployment options for maven and docker.
Docker setup of remoting agent has been debugged.
Also a yamllint check was done on the workflows.
When migrating from a maven to a github-action-based docker build based on release branches and tags, two glitches at the docker artifacts (not the maven artifacts) have been introduced. This PR solves the glitches as well as the opportunity to fix them in all future releases.
Closes #44 <-- _insert Issue number if one exists_
> chore|fix(remoting): Enhance manual build trigger and fix docker glitches due to migrating from maven to github actions

- .github/workflows/build.yml
- .github/workflows/helm-chart-lint.yml
- .github/workflows/helm-chart-release.yml
- .github/workflows/kics.yml
- .github/workflows/trivy.yml
- .github/workflows/veracode.yml
- remoting/pom.xml
- remoting/src/main/docker/Dockerfile
Fixes docker build for release versions to include a callbackhandler feature/binary (which was tried to be copied with a SNAPSHOT in the jar name and which was lacking a META-INF manifest).
Adapts the workflows to be conformant to yamllint and allow for more options when doing a manual triggering.
#44  
the merger could be so kind to manually trigger the build.yml workflow after the merge, such that the docker images are updated (maven packages are perfect).
Closes #44
> fix(workflows|docker): Lacking feature/binary in release image, extend workflows to be able to patch it.

- .github/workflows/build.yml
- .github/workflows/trivy.yml
solves a copy&paste error when overtaking workflow code from a sibling repository
trivy and build workflows do not behave correctly.
after the merge, the build workflow should be started manually once (in order to deploy to docker, but not to maven).
see https://github.com/eclipse-tractusx/knowledge-agents/actions/runs/6467024646
> fix(workflows): copy&paste error from sibling repository.

- .github/workflows/build.yml
- .github/workflows/trivy.yml
Correcty two repository name references which were copied from workflows of a sibling repository.
build and trivy would not run correctly.
No manuel intervention after merge necessary.
see https://github.com/eclipse-tractusx/knowledge-agents/actions/runs/6467024646
> PRIO-1 fix(workflows): correct copy&paste error from sibling repository

- pom.xml
Reintroduce the spotless plugin definition.
When introducing checkstyle, the spotless plugin had been replaced/disabled.
Spotless check is part of the veracode workflow.
see https://github.com/eclipse-tractusx/knowledge-agents/actions/runs/6952127226
Could you please invoke https://github.com/eclipse-tractusx/knowledge-agents/actions/workflows/veracode.yml afterwards.
> chore: need to (re-)enable spotless for veracode

- conforming/README.md
- provisioning/README.md
- remoting/README.md
This PR reformats the "Notice for Docker image" section to use bullet point for general project info.
Single line-breaks in markdown will be ignored and the whole project info was shown on a single line, which makes it hard to read.
Also reformatted markdown table via plugin to read nicely in raw format. Also removed trailing spaces
> fix(docs): add linebreaks in docker notice

- .github/workflows/build.yml
- CHANGELOG.md
- DEPENDENCIES
- charts/conforming-agent/Chart.yaml
- charts/conforming-agent/README.md
- charts/provisioning-agent/Chart.yaml
- charts/provisioning-agent/README.md
- charts/remoting-agent/Chart.yaml
- charts/remoting-agent/README.md
- conforming/README.md
- conforming/pom.xml
- pom.xml
- provisioning/README.md
- provisioning/pom.xml
- provisioning/src/main/docker/Dockerfile
- remoting/README.md
- remoting/pom.xml
- remoting/src/main/docker/Dockerfile
- upgrade_version.sh
remove -SNAPSHOT suffix from versions before tagging the release. extend changelog.
release will have no -SNAPSHOT suffix.
DEPENDENCIES need be updated
One dependency/IP check is still open before this can be merged and tagged.
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11624
> chore: prepare release.

- provisioning/README.md
- provisioning/resources/cx-ontology.ttl
- provisioning/resources/cx-ontology.xml
- provisioning/resources/entrypoint.sh
- provisioning/resources/portal.toml
- provisioning/resources/settings.properties
- provisioning/src/main/docker/Dockerfile
need to port entrypoint script to ash expressions as busybox alpine will not be bash compatible.
curently the chart test fails (without special configuraton or mount overrides).
Closes #75
> fix: problems with busybox default shell on linux/amd64. 

- .github/workflows/helm-chart-lint.yml
- .github/workflows/veracode.yml
- DEPENDENCIES
- provisioning/README.md
- provisioning/pom.xml
- provisioning/resources/entrypoint.sh
- provisioning/src/main/docker/Dockerfile
This fix resolves two issues with the provisioning agent which appeared during the E2E Test 24.03 (shell script & JRE platform).
It also documents the version changes (on logback) and hardening efforts (on spring web) between the 1.10 and 1.11 lines.
Some github actions have been upgraded, too.
Due to an erroneous command line, the ontology configurations were not taken from the environment variables correctly for all endpoints but the last.
Furthermore, when working against a virtualizer, such as dremio, the jdbc drives included in the image need to be compatible with the JRE version (else their network stack could run into connection problems).
Dremio switched their driver model in a later/more current version from a proprietary to an open-source based generic one.
We should have a look …
> fix: Provisioning Agent Ontology Configuration & JRW Compatibility with Dremio Drivers

- .github/workflows/codeql.yml
This PR introduces an open-source SAST tool called **CodeQL** which is native to GitHub.
This is requested as part of the transition from commercial tool vendor to an open source tool that offers better GitHub integration, at no extra cost, making our security setup more efficient.
CodeQL will be added as a mandatory tool to perform SAST scans as part of the TRG 8.0 Security.
Essentially, the support from Veracode as a commercial vendor will come to an end. Hence it is important to run CodeQL as the recommended scanning tool for static code analysis.
> feature: SAST Scans using CodeQL

- matchmaking/src/main/java/org/eclipse/tractusx/agents/AgentConfig.java
- matchmaking/src/main/java/org/eclipse/tractusx/agents/http/DelegationServiceImpl.java
Improves url and header checking in AgentConfig.
CodeQL complains about some potential SSF traps.
Wrt to sanitizing other dynamic SSF sources which CodeQL may not correctly detect, please have a look at:
- https://github.com/eclipse-tractusx/knowledge-agents/blob/05827e257934542c8015201611f0d43c37944d71/matchmaking/src/main/java/org/eclipse/tractusx/agents/http/GraphController.java#L155 ff
-  https://github.com/eclipse-tractusx/knowledge-agents/blob/05827e257934542c8015201611f0d43c37944d71/matchmaking/src/main/java/org/eclipse/tractusx/agents/http/DelegationServiceImpl.java#L215 ff
- https://github.com/eclipse-tractusx/knowledge-agents/blob/05827e257934542c8015201611f0d43c37944d71/matchmaking/src/main/java/org/eclipse/tractusx/agents/http/DelegationServiceImpl.java#L219 ff
Closes #128
> fix: check connector urls and headers coming from config.

- CONTRIBUTING.md
- DEPENDENCIES
- LICENSE
- LICENSE_non-code
- NOTICE.md
added Terms of Use in CONTRIBUTING file
extended NOTICE file with a notice for the CC-BY-4.0 license
added the CC-BY-4.0 license to the root repository as default license for non-code artifacts
upped the version to prepare TX/CX 24.08 release.
Updates due to changes in TRG 7:
Closes #135  <-- _insert Issue number if one exists_
> fix: #135 license issues

- .github/workflows/build.yml
- README.md
- charts/conforming-agent/Chart.yaml
- charts/conforming-agent/README.md
- charts/conforming-agent/values.yaml
- charts/matchmaking-agent/Chart.yaml
- charts/matchmaking-agent/README.md
- charts/matchmaking-agent/ci/integration-values.yaml
- charts/provisioning-agent/Chart.yaml
- charts/provisioning-agent/README.md
- charts/remoting-agent/Chart.yaml
- charts/remoting-agent/README.md
- conforming/README.md
- conforming/pom.xml
- matchmaking/README.md
- matchmaking/pom.xml
- pom.xml
- provisioning/README.md
- provisioning/pom.xml
- remoting/README.md
- remoting/pom.xml
- upgrade_version.sh
Prepare final tagging by using non-SNAPSHOT versions.
Requirement to build the final artifacts.
_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method signature changes, package declarations, bugs that were encountered and were fixed inline, etc._
Closes # <-- _insert Issue number if one exists_
> chore: upgrade to non-SNAPSHOT release version

- .github/workflows/build.yml
- .github/workflows/helm-chart-lint.yml
- CHANGELOG.md
- conforming/README.md
- conforming/src/main/docker/Dockerfile
- matchmaking/README.md
- matchmaking/src/main/docker/Dockerfile
- remoting/README.md
- remoting/src/main/docker/Dockerfile
Update base image and add multi-platform support to pipeline.
Improve TRG compliance.
_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method signature changes, package declarations, bugs that were encountered and were fixed inline, etc._
Closes # <-- _insert Issue number if one exists_
> chore: update base images and multi-platform support.
